#!/usr/bin/env python3
# from typing import *



# def solve(N: int, a: List[int]) -> int:
def solve(N, a):
    alice = 0
    bob = 0
    for i in range(N):
        v_max = max(a)
        if i % 2 == 0:
            alice += v_max
        else:
            bob += v_max
        a.remove(v_max)
        
    return alice - bob
        
        

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = list(map(int, input().split()))
    a1 = solve(N, a)
    print(a1)

if __name__ == '__main__':
    main()
