#!/usr/bin/env python3
# from typing import *



# def solve(N: int, A: List[int]) -> int:
def solve(N, A):
    count = 0
    while all(i % 2 == 0 for i in A):
        A = [j // 2 for j in A]
        count += 1
    return count

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, A)
    print(a)

if __name__ == '__main__':
    main()
