#!/usr/bin/env python3
# from typing import *



# def solve(n: int, a: List[int]) -> int:
def solve(n):
    return n.count('1')

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    n = input() 
    a = solve(n)
    print(a)

if __name__ == '__main__':
    main()
