#!/usr/bin/env python3
# from typing import *



# def solve(N: int, Y: int) -> Tuple[int, int, int]:
def solve(N, Y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Y = map(int, input().split())
    d, e, f = solve(N, Y)
    print(d, e, f)

if __name__ == '__main__':
    main()
