#!/usr/bin/env python3
# from typing import *



# def solve(N: int, Y: int) -> Tuple[int, int, int]:
def solve(N, Y):
    for i in range(0, N + 1):
        for j in range(0, (N + 1 - i)):
            k = N - i - j
            if Y == (i * 10000) + (j * 5000) + (k * 1000):
                return (i, j, k)
    return (-1, -1, -1)

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Y = map(int, input().split())
    d, e, f = solve(N, Y)
    print(d, e, f)

if __name__ == '__main__':
    main()
