#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, t: List[int], x: List[int], y: List[int]) -> str:
def solve(N, t, x, y):
    current_t = 0
    current_x = 0
    current_y = 0
    for i in range(N):
        dt = t[i] - current_t
        d = abs(x[i] - current_x) + abs(y[i] - current_y)
        if d > dt:
            return NO
        if (dt - d) % 2 == 1:
            return NO
        
        current_t = t[i]
        current_x = x[i]
        current_y = y[i]
    return YES
            

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    t = [None for _ in range(N)]
    x = [None for _ in range(N)]
    y = [None for _ in range(N)]
    for i in range(N):
        t[i], x[i], y[i] = map(int, input().split())
    a = solve(N, t, x, y)
    print(a)

if __name__ == '__main__':
    main()
