#!/usr/bin/env python3
# from typing import *



# def solve(N: int, A: int, B: int) -> int:
def solve(N, A, B):
    total_sum = 0
    for i in range(1, N + 1):
        digit_sum = sum(map(int, str(i)))
        if A <= digit_sum <= B:
            total_sum += i
    return total_sum 
            

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, B = map(int, input().split())
    a = solve(N, A, B)
    print(a)

if __name__ == '__main__':
    main()
