#!/usr/bin/env python3
# from typing import *



# def solve(N: int, A: int, B: int) -> int:
def solve(N, A, B):
    sum = 0
    for i in range(1, N + 1):
        digitsum = 0
        temp = i
        while temp:
            digitsum += temp % 10
            temp //= 10
        if A <= digitsum and digitsum <= B:
            sum += i
    return sum
            

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, B = map(int, input().split())
    a = solve(N, A, B)
    print(a)

if __name__ == '__main__':
    main()
